### ISSUE TITLE
More control functionality? eg skip track

### ISSUE THREAD

**Issue by sir-ragna** [usrbinnc/netcat-cpi-kernel-module#12]
Would it be possible to add some more functionality to the player by writing to the stream device? Some examples below. 

```
/dev/netcat play    # could be used to resume playing
/dev/netcat pauze   # could pauze the playing
/dev/netcat play 2  # could start playing track 2
/dev/netcat loop
/dev/netcat noloop
/dev/netcat shuffle
```

**Comment by blucia0a** [comment]
That is a great idea!  I'm not sure the best way to do this, but I'll give this feature request some thought.

**Comment by deed02392** [comment]
Given how we typically talk to devices, wouldn't this be more appropriate :

`echo "play" > /dev/netcat`

**Comment by ackalker** [comment]
To keep in style, you could define some extra ioctl() requests for this ;-)

**Comment by sir-ragna** [comment]
What @deed02392 said. Write text to the device like you usually would.
