### ISSUE TITLE
Slackware and vlc compatibility

### ISSUE THREAD

**Issue by filviu** [usrbinnc/netcat-cpi-kernel-module#24]
Hi,

Just wanted to let you know it builds and runs fine under slackware64-current. 

Also I got an issue on my particular hardware when using ogg123:
ao_alsa WARNING: sample rate 22050 not supported by the hardware, using 44100
and the sound was choppy.

Using vlc/cvlc instead of ogg123 allowed for smooth playback. 

Thanks a bunch !

**Comment by blucia0a** [comment]
Added a note about this to the README.  Thanks for checking out our album!

**Comment by 01micko** [comment]
I concur but on 32 bit slackware-14.1, same alsa warning apparent only on the first track. However sound was ok with other tracks.
