### ISSUE TITLE
Song playing too fast

### ISSUE THREAD

**Issue by fpeterschmitt** [usrbinnc/netcat-cpi-kernel-module#26]
Hi,

I'm running Debian sid amd64 and I noticed it is playing much too fast.

Instead of running for 17 minutes, it just run around the half time.

**Comment by blucia0a** [comment]
Interesting, I haven't seen that show up anywhere.  What program are you using to play the album?   Try it with ogg123 -- we've been testing against that.

**Comment by n5rgn** [comment]
Did you use the Intel compiler (icc)?  For Intel processors it can generate code that runs at least 20% faster, especially with -O3.

;)

**Comment by fpeterschmitt** [comment]
Nope, GCC 4.8

Le 30/04/2014 17:29, sansneural a écrit :

> Did you use the Intel compiler (icc)?  For Intel processors it can generate code that runs at least 20% faster, especially with -O3.
> 
> ;)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/usrbinnc/netcat-cpi-kernel-module/issues/26#issuecomment-41810870

## 

Florent Peterschmitt           | Please:
florent@peterschmitt.fr        |  \* Avoid HTML/RTF in E-mail.
http://florent.peterschmitt.fr |  \* Send PDF for documents.
Proudly powered by FLOSS       |  \* Trim your quotations. Really.
                               | Thank you :)

**Comment by freddix** [comment]
I can hear the "speedy" version on my box using ogg123. When using mpv all sounds good here. Not a netcat bug.

Might be related to:

```
Ogg Vorbis stream: 2 channel, 22050 Hz
ao_alsa WARNING: sample rate 22050 not supported by the hardware, using 44100
```

**Comment by notklaatu** [comment]
ogg123 was also resulting in stuttered/fast playback for me. ffplay works though.  

```
ffplay - < /dev/netcat
```
