### ISSUE TITLE
"left but not entered" errors on compile

### ISSUE THREAD

**Issue by dmarti** [usrbinnc/netcat-cpi-kernel-module#35]
I'm able to build and play this module but getting some errors, using
gcc (GCC) 4.8.2 20131212 (Red Hat 4.8.2-7)

line-map.c: file "/home/dmarti/Software/netcat-cpi-kernel-module/tracks/trk2.h" left but not entered
line-map.c: file "/home/dmarti/Software/netcat-cpi-kernel-module/netcat.c" left but not entered
line-map.c: file "/home/dmarti/Software/netcat-cpi-kernel-module/tracks/trk3.h" left but not entered
line-map.c: file "/home/dmarti/Software/netcat-cpi-kernel-module/netcat.c" left but not entered

**Comment by gregkh** [comment]
On Fri, Apr 25, 2014 at 12:39:27PM -0700, Don Marti wrote:

> I'm able to build and play this module but getting some errors, using
> gcc (GCC) 4.8.2 20131212 (Red Hat 4.8.2-7)
> 
> line-map.c: file "/home/dmarti/Software/netcat-cpi-kernel-module/tracks/trk2.h"
> left but not entered

Where does "line-map.c" come from?  That's not part of this package.

**Comment by dmarti** [comment]
I don't have a "line-map.c" on my system either.  The only mention of this file I found in a web search was this thread... 
http://stackoverflow.com/questions/1852788/what-causes-the-left-but-not-entered-gcc-compiler-error

**Comment by blucia0a** [comment]
I'm going to close this issue because it sounds like a compiler configuration error.
