### ISSUE TITLE
useless use of cat

### ISSUE THREAD

**Issue by jmtd** [usrbinnc/netcat-cpi-kernel-module#6]
Documentation reads

```
cat /dev/netcat | ogg123 -
```

The `cat` is superfluous. Consider

```
ogg123 - </dev/netcat
```

Or possibly

```
ogg123 /dev/netcat
```

**Comment by blucia0a** [comment]
Thanks for that note.  I expect ogg123 - < /dev/netcat will work, so I will add that to the readme today to eliminate the superfluous 'cat'.

**Comment by dbalatero** [comment]
@jmtd `ogg123 /dev/netcat` didn't work, but `ogg123 - </dev/netcat` worked just fine

**Comment by blucia0a** [comment]
It's an extra process, but I find using cat here more readable.

**Comment by dbalatero** [comment]
Yeah I don't mind either way, the more I think about it.

**Comment by blucia0a** [comment]
I addressed this in netcat.c and the README.
