### ISSUE TITLE
-I flag not getting passed to compiler

### ISSUE THREAD

**Issue by athas** [usrbinnc/netcat-cpi-kernel-module#7]
On my Debian system running kernel 3.2.0-3-amd64, the extra CFLAGS in the Makefile do not get passed to the compiler, resulting in the track header files not being found.

**Comment by blucia0a** [comment]
I'll look into this.  On Ubuntu I had to dig to fins the extra_cflags make var.  I suspect on your system that var has a different name...

**Comment by jnwatts** [comment]
@Athas: This might be solved by #16, you should give it a try

**Comment by blucia0a** [comment]
Closing this because @gregkh's pull request fixes this issue.
